import { Container, ContainerProxy, getContainer } from "@cloudflare/containers";
import { env } from "cloudflare:workers";

// The outbound handlers below run inside this entrypoint; the library reaches
// them through ctx.exports, so it MUST be exported from the main module.
export { ContainerProxy };

/**
 * `Env` itself is generated by `wrangler types` from wrangler.jsonc (it carries
 * SYNC_CONTAINER, the DELIVERIT service binding and every entry in `vars`). Secrets
 * are not in that file, so they are merged in here.
 */
declare global {
  interface Env {
    // Set with `wrangler secret put`, never in wrangler.jsonc.
    SYNC_KEY: string;
    SYNC_KEY_PREVIOUS?: string;
    CLICKUP_TOKEN: string;
    PRODUCTIVE_TOKEN: string;
    PRODUCTIVE_ORG_ID: string;
    // Optional: without it the DeliverIT stage is off with a warning, and the
    // ClickUp -> Productive sync runs as before.
    DELIVERIT_API_KEY?: string;
  }
}

/**
 * Config keys forwarded into the container as environment variables.
 *
 * The Go binary carries compiled-in defaults for every id and label, so only the
 * three credentials are strictly required.
 *
 * Two secrets are deliberately ABSENT and never reach the container, where they
 * would end up in container logs, `/proc/self/environ` and any `wrangler containers
 * ssh` session:
 *   - SYNC_KEY — the gateway key; only the Worker checks it.
 *   - DELIVERIT_API_KEY — only the outbound handler below uses it: the container
 *     calls http://deliverit.internal WITHOUT credentials and the handler sets
 *     Authorization on its way to DeliverIT over the service binding. The key never
 *     travels in a request from the container either, so it cannot land in Workers
 *     Logs as a request header of the handler invocation.
 * What the container does get is DELIVERIT_API_KEY_PREFIX (containerEnvVars), so
 * it can tell "not configured" from "configured" and name the key in logs.
 */
const CONTAINER_ENV_KEYS = [
  "CLICKUP_TOKEN",
  "PRODUCTIVE_TOKEN",
  "PRODUCTIVE_ORG_ID",
  // Overridable so `wrangler dev` can be pointed at a stub instead of production.
  "CLICKUP_BASE_URL",
  "PRODUCTIVE_BASE_URL",
  "CLICKUP_LIST_ID",
  "PRODUCTIVE_PROJECT_ID",
  "PRODUCTIVE_TASK_LIST_ID",
  "PRODUCTIVE_CF_CLICKUP_ID",
  "PRODUCTIVE_CF_CLICKUP_TAGS",
  "PRODUCTIVE_STATUS_OPEN_ID",
  "PRODUCTIVE_STATUS_DONE_ID",
  "PRODUCTIVE_DONE_STATUS_NAMES",
  "CLICKUP_DONE_STATUSES",
  "CLICKUP_ESTIMATE_FIELD_IDS",
  "CLICKUP_ESTIMATE_LABEL_MINUTES",
  "CLICKUP_INCLUDE_CLOSED",
  "MERGE_CUSTOM_FIELDS",
  "ALLOW_REPARENT",
  "ESTIMATE_CLEAR_MODE",
  "PRODUCTIVE_RPS",
  "PRODUCTIVE_BURST_RPS",
  "CLICKUP_RPS",
  "MAX_CREATES",
  "MAX_WRITES",
  "MAX_RETRIES",
  "SYNC_TIMEOUT",
  "LOG_LEVEL",
  // DeliverIT fanout. "" = stage off. In production http://deliverit.internal, the
  // virtual host handled by deliverITOutbound below.
  "DELIVERIT_BASE_URL",
  "DELIVERIT_RPS",
] as const;

function containerEnvVars(): Record<string, string> {
  const source = env as unknown as Record<string, unknown>;
  const out: Record<string, string> = {};
  for (const key of CONTAINER_ENV_KEYS) {
    const value = source[key];
    if (typeof value === "string" && value !== "") out[key] = value;
  }
  const deliverITKey = source["DELIVERIT_API_KEY"];
  if (typeof deliverITKey === "string" && deliverITKey.trim() !== "") {
    out["DELIVERIT_API_KEY_PREFIX"] = deliverITKeyPrefix(deliverITKey.trim());
  }
  return out;
}

/**
 * "dit_" + 8 characters — DeliverIT's ApiKey.KeyPrefix, the string it shows in
 * /integracje and logs as `user=api-key:dit_…`. "invalid" makes the container
 * report a malformed secret instead of calling DeliverIT with it.
 */
function deliverITKeyPrefix(key: string): string {
  return /^dit_[A-Za-z0-9_-]{9,}$/.test(key) ? key.slice(0, 12) : "invalid";
}

/**
 * Must stay above the container's SYNC_TIMEOUT (default 10m) so the lease cannot
 * expire while the Go process is still writing, and comfortably below the 15
 * minutes Cloudflare allows between SIGTERM and SIGKILL.
 */
const LEASE_TTL_MS = 11 * 60_000;

interface Lease {
  runId: string;
  startedAt: number;
  until: number;
}

export class SyncContainer extends Container<Env> {
  defaultPort = 8080;

  /**
   * Backstop ONLY. sleepAfter is measured against activity at the Durable Object,
   * not against work happening inside the container: with a short value the
   * expiry hook fires mid-sync and SIGTERMs the Go process. A generous value plus
   * the explicit stop() below means the container dies right after a run rather
   * than being killed during one.
   *
   * onActivityExpired is deliberately NOT overridden. Polling the container from
   * that hook is a trap — containerFetch() STARTS a stopped container, so a poll
   * after a crash would boot a fresh one every few minutes, forever.
   */
  sleepAfter = "20m";

  envVars = containerEnvVars();

  override onStop({ exitCode, reason }: { exitCode: number; reason: string }): void {
    // exitCode 137 is OOM, 0 is a clean exit. Without this they look identical
    // from the Worker side.
    console.log(JSON.stringify({ msg: "container stopped", exitCode, reason }));
  }

  override onError(error: unknown): never {
    console.log(JSON.stringify({ msg: "container error", error: String(error) }));
    throw error;
  }

  /**
   * The lease lock lives here because the Durable Object is the only thing in this
   * architecture with state that survives a container restart.
   *
   * A mutex inside the Go process cannot prevent the expensive case: during a
   * rollout or a host recycle the old process has 15 minutes to drain while the DO
   * routes new requests to its replacement. Two runs would then each read
   * Productive before either wrote, and both would POST the same task — and since
   * the ClickUp id is only written as part of the POST, that duplicate cannot be
   * detected beforehand and is painful to unpick afterwards.
   */
  override async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/status") return this.handleStatus(request);

    const now = Date.now();
    const lease = await this.ctx.storage.get<Lease>("lease");
    if (lease && lease.until > now) {
      return jsonResponse(409, {
        error: "a sync is already running",
        active: { run_id: lease.runId, started_at: new Date(lease.startedAt).toISOString() },
      });
    }

    const runId = crypto.randomUUID();
    await this.ctx.storage.put<Lease>("lease", {
      runId,
      startedAt: now,
      until: now + LEASE_TTL_MS,
    });

    let completed = false;
    try {
      const upstream = await this.fetchReadyContainer(request);
      // Buffer BEFORE stopping the container: an unbuffered stream out of a
      // SIGTERMed process yields a truncated body.
      const body = await upstream.arrayBuffer();
      completed = true;

      await this.ctx.storage.put("lastRun", {
        runId,
        finishedAt: new Date().toISOString(),
        status: upstream.status,
        summary: safeParse(body),
      });

      const headers = new Headers(upstream.headers);
      headers.set("Cache-Control", "no-store, private");
      return new Response(body, { status: upstream.status, headers });
    } finally {
      if (completed) {
        await this.ctx.storage.delete("lease");
        try {
          // Scale to zero immediately instead of paying for the sleepAfter tail.
          await this.stop();
        } catch (error) {
          console.log(JSON.stringify({ msg: "stop failed; sleepAfter will reap", error: String(error) }));
        }
      }
      // On an aborted request the lease is left to expire on its own. The Go
      // process runs on a context detached from the request, so it is still
      // working; releasing the lease early would let a retry overlap it, and
      // calling stop() would kill it mid-write.
    }
  }

  /**
   * containerFetch() does not wait for the container to be ready. Immediately
   * after the stop() below, the process is gone but the instance still exists, and
   * a plain containerFetch() fails with "Container is not listening to port 8080"
   * (the error is flagged retryable). Verified against `wrangler dev`: the second
   * consecutive GET /sync returned 500 until this was added.
   *
   * startAndWaitForPorts() is the documented way to block until the process
   * accepts connections — 8s to get an instance, 20s for the port, against a
   * 1-3s cold start.
   */
  private async fetchReadyContainer(request: Request): Promise<Response> {
    let lastError: unknown;
    for (let attempt = 0; attempt < 3; attempt++) {
      try {
        await this.startAndWaitForPorts();
        return await this.containerFetch(request);
      } catch (error) {
        lastError = error;
        console.log(
          JSON.stringify({ msg: "container not ready; retrying", attempt: attempt + 1, error: String(error) }),
        );
        await scheduler.wait(1000 * (attempt + 1));
      }
    }
    throw lastError;
  }

  private async handleStatus(request: Request): Promise<Response> {
    const [lease, lastRun, state] = await Promise.all([
      this.ctx.storage.get<Lease>("lease"),
      this.ctx.storage.get("lastRun"),
      this.getState(),
    ]);

    // Only talk to the container when it is already up. containerFetch() would
    // START a stopped one, which turns a status poll into a billable boot.
    let live: unknown = null;
    if (state.status === "healthy") {
      try {
        const res = await this.containerFetch(request);
        live = safeParse(await res.arrayBuffer());
      } catch (error) {
        live = { error: String(error) };
      }
    }

    return jsonResponse(200, {
      container: state.status,
      lease: lease ?? null,
      lease_active: !!lease && lease.until > Date.now(),
      last_run: lastRun ?? null,
      live,
    });
  }
}

// --- DeliverIT: container -> outbound handler -> service binding ---

/**
 * The virtual host the container calls (deliverITProxyHost in
 * container_src/deliverit.go). A ".internal" name never resolves publicly, so a
 * misconfiguration fails instead of sending anything elsewhere.
 */
const DELIVERIT_PROXY_HOST = "deliverit.internal";

/**
 * Part of the DeliverIT Worker's contract: over http it answers POST with 400
 * MALFORMED_REQUEST and GET with a 308, and .NET checks AllowedHosts.
 */
const DELIVERIT_ORIGIN = "https://internal.deliverit.pl";

/** The ONLY two routes the key opens, and the only two the handler forwards. */
const DELIVERIT_ROUTES: ReadonlyArray<{ method: string; path: RegExp }> = [
  { method: "GET", path: /^\/api\/integrations\/projects$/ },
  {
    method: "POST",
    path: /^\/api\/integrations\/projects\/[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}\/tasks\/sync$/,
  },
];

/** Everything else (CF-*, X-Forwarded-*, Origin, Sec-Fetch-*) stays behind. */
const DELIVERIT_FORWARDED_HEADERS = ["Content-Type", "Accept", "User-Agent"] as const;

/**
 * Why a service binding and not the public internet (README „Fanout do DeliverIT”):
 *   - direct egress from the container goes through the deliverit.pl zone's Bot
 *     Fight Mode / Browser Integrity Check / WAF, and on the Free plan Bot Fight
 *     Mode cannot be skipped by a rule; IP Access needs a fixed IP, which
 *     Containers do not have;
 *   - `fetch("https://internal.deliverit.pl")` from THIS Worker is a cross-zone
 *     subrequest whose CF-Connecting-IP is 2a06:98c0:3600::103 — shared by every
 *     Worker of every Cloudflare customer, i.e. one bucket in DeliverIT's per-IP
 *     rate limiter with strangers. Never do that.
 * Over the binding the request never leaves Cloudflare and never touches the zone.
 */
async function deliverITOutbound(request: Request, workerEnv: Env): Promise<Response> {
  const url = new URL(request.url);
  const allowed = DELIVERIT_ROUTES.some((route) => route.method === request.method && route.path.test(url.pathname));
  if (!allowed || url.search !== "") {
    return problemResponse(403, "OUTBOUND_ROUTE_DENIED",
      "pcuintegrator forwards only GET /api/integrations/projects and POST /api/integrations/projects/{id}/tasks/sync.");
  }

  const key = workerEnv.DELIVERIT_API_KEY?.trim();
  if (!key) {
    // The container does not call without DELIVERIT_API_KEY_PREFIX; this is the
    // backstop. UNAUTHENTICATED stops the stage without retries.
    return problemResponse(401, "UNAUTHENTICATED", "Worker secret DELIVERIT_API_KEY is not set.");
  }

  // A NEW request: nothing from the container's request reaches DeliverIT except
  // the path, the body and the three headers below. Authorization is SET, never
  // appended, so the container cannot smuggle its own.
  const headers = new Headers();
  for (const name of DELIVERIT_FORWARDED_HEADERS) {
    const value = request.headers.get(name);
    if (value !== null) headers.set(name, value);
  }
  headers.set("Authorization", `Bearer ${key}`);
  const body = request.method === "GET" ? undefined : await request.arrayBuffer();
  const forwarded = new Request(DELIVERIT_ORIGIN + url.pathname, {
    method: request.method,
    headers,
    body,
    redirect: "manual",
  });

  try {
    // Passed through untouched: 429/503 keep their Retry-After, 413 its empty body.
    return await workerEnv.DELIVERIT.fetch(forwarded);
  } catch (error) {
    // e.g. the `deliverit-internal` Worker is missing. 502 is retried like the
    // Worker's own cold-start answers.
    console.log(JSON.stringify({ msg: "deliverit service binding failed", error: String(error) }));
    return problemResponse(502, "DELIVERIT_BINDING_FAILED", "The DELIVERIT service binding failed.");
  }
}

// Only this host is intercepted; ClickUp and Productive traffic still goes
// straight to the internet (enableInternet stays at its default, true).
SyncContainer.outboundByHost = { [DELIVERIT_PROXY_HOST]: deliverITOutbound };

export default {
  /**
   * The only public surface: `GET /sync` and `GET /status`, both requiring
   * `Authorization: Bearer <SYNC_KEY>`.
   */
  async fetch(request: Request, workerEnv: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname !== "/sync" && url.pathname !== "/status") {
      return jsonResponse(404, { error: "not found" });
    }

    // HEAD in particular must be rejected: uptime monitors love it, and it would
    // run a full production sync and throw the body away.
    if (request.method !== "GET") {
      return jsonResponse(405, { error: "method not allowed" }, { Allow: "GET" });
    }
    if (request.body !== null) {
      return jsonResponse(400, { error: "unexpected request body" });
    }

    // Auth first: the 401 path must never reach getContainer(), so an
    // unauthenticated caller can never make us start a container.
    if (!(await authorized(request, workerEnv))) {
      return jsonResponse(401, { error: "unauthorized" });
    }

    // Rebuild the request without the credential. container.fetch() forwards the
    // ORIGINAL request, which would put the gateway key into container logs. The
    // query string (?dry_run=true&explain=true&max_creates=N) is preserved.
    const forwarded = new Request(url.toString(), { method: "GET" });

    try {
      return await getContainer(workerEnv.SYNC_CONTAINER).fetch(forwarded);
    } catch (error) {
      // A container that fails to start (max_instances reached, provisioning still
      // in progress after a first deploy) otherwise surfaces as an opaque 500.
      console.log(JSON.stringify({ msg: "container unavailable", error: String(error) }));
      return jsonResponse(503, { error: "container unavailable", detail: String(error) });
    }
  },

  /**
   * Cron replacement for the .NET PeriodicTimer(4h). Awaiting matters: it is what
   * lets the Durable Object's finally block release the lease and stop the
   * container. A scheduled invocation is hard-killed at 15 minutes of wall time,
   * which is why the container's own SYNC_TIMEOUT must stay at or below 12m.
   */
  async scheduled(_controller: ScheduledController, workerEnv: Env): Promise<void> {
    const request = new Request("https://sync.internal/sync", { method: "GET" });
    try {
      const res = await getContainer(workerEnv.SYNC_CONTAINER).fetch(request);
      console.log(JSON.stringify({ msg: "cron sync finished", status: res.status, body: await res.text() }));
    } catch (error) {
      console.log(JSON.stringify({ msg: "cron sync failed", error: String(error) }));
    }
  },
} satisfies ExportedHandler<Env>;

// --- auth ---

function bearer(header: string | null): string | null {
  if (!header) return null;
  const match = /^Bearer\s+(.+)$/i.exec(header.trim());
  const token = match?.[1]?.trim();
  return token ? token : null;
}

async function authorized(request: Request, workerEnv: Env): Promise<boolean> {
  // Header only, never a query parameter. That single rule is why link unfurlers,
  // email scanners and browser history cannot trigger a production sync.
  const provided = bearer(request.headers.get("Authorization"));
  if (!provided) return false;

  const candidates = [workerEnv.SYNC_KEY, workerEnv.SYNC_KEY_PREVIOUS].filter(
    (k): k is string => typeof k === "string" && k.length > 0,
  );

  let ok = false;
  for (const candidate of candidates) {
    // No early return: keep the work constant across candidates.
    if (await constantTimeEqual(provided, candidate)) ok = true;
  }
  return ok;
}

/**
 * crypto.subtle.timingSafeEqual throws on unequal byte lengths, which is both a
 * length oracle and a crash. Hashing first makes both sides exactly 32 bytes.
 */
async function constantTimeEqual(a: string, b: string): Promise<boolean> {
  const encoder = new TextEncoder();
  const [ha, hb] = await Promise.all([
    crypto.subtle.digest("SHA-256", encoder.encode(a)),
    crypto.subtle.digest("SHA-256", encoder.encode(b)),
  ]);
  return crypto.subtle.timingSafeEqual(ha, hb);
}

// --- helpers ---

function jsonResponse(status: number, body: unknown, extraHeaders: Record<string, string> = {}): Response {
  return new Response(JSON.stringify(body, null, 2) + "\n", {
    status,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      // A "Cache Everything" rule on the zone would otherwise serve a stale 200
      // and the sync would silently never run.
      "Cache-Control": "no-store, private",
      ...extraHeaders,
    },
  });
}

/** application/problem+json in the shape the Go client (and DeliverIT itself) uses. */
function problemResponse(status: number, code: string, detail: string): Response {
  return new Response(JSON.stringify({ type: "about:blank", title: "pcuintegrator", status, detail, code }), {
    status,
    headers: { "Content-Type": "application/problem+json; charset=utf-8", "Cache-Control": "no-store" },
  });
}

function safeParse(body: ArrayBuffer): unknown {
  try {
    return JSON.parse(new TextDecoder().decode(body));
  } catch {
    return null;
  }
}
